---
- name: delete gcp resources
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: delete firewall rule (wireguard)
      gcp_compute_firewall:
        name: "{{ gcp_fr_name }}"
        project: "{{ gcp_project_id }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file_dir }}/{{ gcp_cred_file }}"
        state: absent

    - name: delete vm instance
      gcp_compute_instance:
        name: "{{ gcp_vm_name }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project_id }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file_dir }}/{{ gcp_cred_file }}"
        state: absent

    - name: delete disk
      gcp_compute_disk:
        name: "{{ gcp_disk_name }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project_id }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file_dir }}/{{ gcp_cred_file }}"
        state: absent
...