---
- name: delete gcp service account and key file
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: check for role attached to service account
      command: >
       gcloud projects get-iam-policy {{ gcp_project_id }} 
       --flatten="bindings[].members" 
       --filter="bindings.members:serviceAccount:
       {{ gcp_svc_acct_id }}@{{ gcp_project_id }}.iam.gserviceaccount.com" 
       --format=text
      changed_when: no
      register: iam_policy

    - name: delete role from service account
      command: >
       gcloud projects remove-iam-policy-binding {{ gcp_project_id }} 
       --member serviceAccount:{{ gcp_svc_acct_id }}@{{ gcp_project_id }}.iam.gserviceaccount.com 
       --role roles/{{ gcp_role }}
      when: gcp_role in iam_policy.stdout

    - name: check for service account
      command: >
       gcloud iam service-accounts describe 
       {{ gcp_svc_acct_id }}@{{ gcp_project_id }}.iam.gserviceaccount.com 
       --project {{ gcp_project_id }}
      ignore_errors: yes
      changed_when: no
      register: svc_acct 

    - name: delete service account
      command: >
       gcloud iam service-accounts delete 
       {{ gcp_svc_acct_id }}@{{ gcp_project_id }}.iam.gserviceaccount.com 
       --project {{ gcp_project_id }}
      when: svc_acct.rc == 0

    - name: delete service account key file and directory
      file:
        path: "{{ gcp_cred_file_dir }}"
        state: absent
...